version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: morozovsk/php-opencv
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    tty: true